### PR TITLE
Fixed corrupted downloads and use $HOME variable instead of full path

### PR DESCRIPTION
**Pull request by STiXzoOR**
As the title says i think i managed to correct the wrong update download( see #2 ) by splitting the **or** statement in the `setPackageMode` function for the `StableVersion` into two separate statements. I also fixed the preferences directory in HOME.

### CODE REVIEW

**Comment by PMheart** [comment]
Hi,

Thanks for the fix for supplemental update! It looks fine to me.
Why download the script to `/usr/bin` though? It's protected by SIP (System Integrity Protection) and thus is unwritable. I think the script can be downloaded anywhere, that's why `curl -O` is written in README.

**Comment by STiXzoOR** [comment]
oh my mistake, i have hackintosh so SIP is disabled that's why i can write to that folder. I did it for convenience so you don't have to write the full path of the script to execute it. I guess you can install it in `/usr/local/bin` and it will do the job.

**Comment by PMheart** [comment]
Well, to be honest, simply double clicking the script (from anywhere) would do the trick. I don't think the script has to be in PATH.

**Comment by STiXzoOR** [comment]
yeah good point fair enough :-)

**Comment by PMheart** [comment]
OK, I will revert the changes regarding path stuffs and merge the PR. Thanks!

**Pull request merged**
