### PR TITLE
updated to support 10.14.4

### PR DESCRIPTION
**Pull request by STiXzoOR**

### CODE REVIEW

**Comment by PMheart** [comment]
Hi, thanks for the update, yet I guess there's a typo: https://github.com/Gengik84/MacOS_Updater/pull/5/commits/c5bc20b6fe04070a180a630243b5314124d3e5cb#diff-7ffc2975bab6aa215aa43525483c5430R472

**Comment by STiXzoOR** [comment]
hi, don't worry it's not a typo. I checked the new catalogs file and the Combo update has the `Auto` string after the version just like the supplemental update.

Screenshot 2019-03-26 at 14 40 37

**Comment by PMheart** [comment]
Yes, but you wrote Aut*P* instead!

**Comment by STiXzoOR** [comment]
oh that one got away i guess sorry ^^

**Comment by PMheart** [comment]
Not a big problem, please correct and it will be fine to merge I guess. :)

**Comment by PMheart** [comment]
Merged, thanks!

**Comment by STiXzoOR** [comment]
Just fixed it :-)

**Pull request merged**
